import { notFound } from "next/navigation";
import { getAnimal } from "@/features/animals/animals";

export default async function AboutPage({ params }: PageProps<"/[animalSlug]/acerca-de">) {
  const { animalSlug } = await params;
  const animal = getAnimal(animalSlug);
  if (!animal) notFound();

  return (
    <section className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-14">
      <div className="max-w-2xl"><p className="text-[10px] font-medium uppercase tracking-[0.16em] text-[#718b78]">Ficha de especie</p><h2 className="mt-2 font-serif text-3xl tracking-[-0.045em] sm:text-4xl">El {animal.commonName.toLowerCase()}</h2><p className="mt-4 text-sm leading-6 text-[#58715f]">{animal.description}</p></div>

      <aside className="mt-8 flex items-center gap-3 rounded-xl border border-[#d8e3d9] bg-[#f1f5ef] p-3 text-[#355d40] sm:max-w-md"><div role="img" aria-label={`Retrato de ${animal.profileReview.reviewer}`} className="size-10 shrink-0 rounded-full bg-[#285d3a] bg-cover bg-center" style={{ backgroundImage: `url('${animal.profileReview.reviewerImage}')` }} /><p className="text-xs leading-5"><span className="font-semibold">Ficha revisada por {animal.profileReview.reviewer}</span><span className="block text-[#67806d]">{animal.profileReview.role} · {animal.profileReview.reviewedAt}</span></p><span className="ml-auto grid size-5 shrink-0 place-items-center rounded-full bg-[#285d3a] text-[10px] text-white">✓</span></aside>

      <div className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
        <section className="relative min-h-[360px] overflow-hidden rounded-2xl bg-[#315a3e] bg-cover bg-center" style={{ backgroundImage: `url('${animal.coverImage}')` }}>
          <div className="absolute inset-0 bg-gradient-to-t from-[#102a1a]/90 via-[#102a1a]/20 to-transparent" />
          <div className="absolute inset-x-0 bottom-0 flex flex-wrap gap-2 p-5 sm:p-7"><span className="rounded-full bg-[#102a1a]/75 px-3 py-1.5 text-[10px] font-medium uppercase tracking-[0.1em] text-white backdrop-blur-sm">Corona azul</span><span className="rounded-full bg-[#102a1a]/75 px-3 py-1.5 text-[10px] font-medium uppercase tracking-[0.1em] text-white backdrop-blur-sm">Antifaz negro</span><span className="rounded-full bg-[#102a1a]/75 px-3 py-1.5 text-[10px] font-medium uppercase tracking-[0.1em] text-white backdrop-blur-sm">Cola en raqueta</span></div>
        </section>
        <section className="flex flex-col justify-center rounded-2xl border border-[#d8e3d9] bg-[#f1f5ef] p-6 sm:p-8"><p className="text-[10px] font-medium uppercase tracking-[0.14em] text-[#708a77]">En La Romera</p><p className="mt-3 font-serif text-2xl leading-8 tracking-[-0.04em] text-[#244a31]">{animal.localPresence}</p></section>
      </div>

      <dl className="mt-4 grid gap-px overflow-hidden rounded-xl border border-[#d8e3d9] bg-[#d8e3d9] sm:grid-cols-3"><div className="bg-[#f8faf6] p-5"><dt className="text-[10px] font-medium uppercase tracking-[0.13em] text-[#708a77]">Hábitat</dt><dd className="mt-2 text-sm leading-6 text-[#355d40]">{animal.habitat}</dd></div><div className="bg-[#f8faf6] p-5"><dt className="text-[10px] font-medium uppercase tracking-[0.13em] text-[#708a77]">Alimentación</dt><dd className="mt-2 font-serif text-xl text-[#244a31]">{animal.diet}</dd></div><div className="bg-[#f8faf6] p-5"><dt className="text-[10px] font-medium uppercase tracking-[0.13em] text-[#708a77]">Conservación</dt><dd className="mt-2 font-serif text-xl text-[#244a31]">{animal.conservationStatus}</dd><p className="mt-1 text-[10px] font-medium uppercase tracking-[0.12em] text-[#708a77]">{animal.statusDetail}</p></div></dl>

      <section className="mt-10 border-t border-[#d8e3d9] pt-8"><div className="max-w-2xl"><p className="text-[10px] font-medium uppercase tracking-[0.16em] text-[#718b78]">Contenido de entidades públicas</p><h3 className="mt-2 font-serif text-2xl tracking-[-0.04em]">La Romera en video</h3><p className="mt-2 text-sm leading-6 text-[#58715f]">Material audiovisual institucional para conocer el territorio que habita esta especie.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2">{animal.publicContent.map((content) => <article key={content.videoId} className="overflow-hidden rounded-xl border border-[#d8e3d9] bg-[#f1f5ef]"><div className="aspect-video bg-[#193b2a]"><iframe className="size-full" src={`https://www.youtube-nocookie.com/embed/${content.videoId}`} title={content.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen /></div><div className="p-4"><p className="text-[10px] font-medium uppercase tracking-[0.13em] text-[#708a77]">Video institucional · {content.duration}</p><h4 className="mt-1 font-serif text-xl leading-tight tracking-[-0.04em] text-[#244a31]">{content.title}</h4></div></article>)}</div><aside className="mt-5 flex items-center gap-4 rounded-xl border border-[#d8e3d9] bg-[#f1f5ef] p-4 sm:max-w-xl"><div role="img" aria-label="Logo de la Alcaldía de Sabaneta" className="size-12 shrink-0 rounded-full bg-white bg-cover bg-center" style={{ backgroundImage: "url('https://www.sabaneta.gov.co/themes/img/17496572236363.png')" }} /><div><p className="text-[10px] font-medium uppercase tracking-[0.13em] text-[#708a77]">Material dispuesto por</p><p className="mt-1 text-sm font-semibold text-[#244a31]">Alcaldía de Sabaneta</p><p className="mt-0.5 text-xs text-[#58715f]">Entidad pública · canal oficial de YouTube</p></div><span className="ml-auto grid size-6 shrink-0 place-items-center rounded-full bg-[#285d3a] text-xs text-white">✓</span></aside></section>
    </section>
  );
}
